package chatbox.springboot.dto;

import java.util.ArrayList;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents the response from ChatGPT API.
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class ChatGPTResponse {
    /**
     * List of Choice objects representing possible choices generated by the AI.
     */
    private ArrayList<Choice> choices;

    /**
     * Represents a choice provided by the AI.
     * Each choice has an associated index and message.
     */
    @Data
    @AllArgsConstructor
    @NoArgsConstructor
    public static class Choice {
        private int index;
        private Message message;
    }
}
